// LOCAL DEV ONLY. Fills the database with clearly fake QAIRU students, boards
// content, chats and attachments for testing and README screenshots.
// Never run against production and never put real student data in here.
import "dotenv/config";
import { and, eq, or, sql } from "drizzle-orm";
import { deflateSync } from "node:zlib";
import { db } from "./index.js";
import {
  users,
  friendships,
  wallPosts,
  boardEvents,
  pokes,
  messages,
  boards,
  discussionPosts,
  discussionComments,
  savedPosts,
  media,
  votes,
  repEvents,
} from "./schema.js";
import { hashPassword } from "../auth/password.js";
import { ensureSchema } from "./migrate.js";
import { castVote, awardReply, awardReferral, setAcceptedAnswer } from "../lib/rep.js";
import { prepareUploads, storeUploads, MEDIA_LIMITS } from "../lib/media.js";
import { makeReferralCode } from "../lib/social.js";

const SEED_PASSWORD = "qairu123";

const hoursAgo = (h: number) => new Date(Date.now() - h * 60 * 60 * 1000);

// ---------------------------------------------------------------------------
// Tiny generated files for attachments (no binary fixtures in the repo).
// ---------------------------------------------------------------------------

const CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c >>> 0;
  }
  return table;
})();

function crc32(bytes: Uint8Array): number {
  let c = 0xffffffff;
  for (const b of bytes) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function pngChunk(type: string, data: Buffer): Buffer {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}

/** A valid size x size PNG: solid colour with a lighter diagonal stripe. */
function makePng(size: number, [r, g, b]: [number, number, number]): Buffer {
  const header = Buffer.alloc(13);
  header.writeUInt32BE(size, 0);
  header.writeUInt32BE(size, 4);
  header[8] = 8; // bit depth
  header[9] = 2; // colour type: truecolour RGB
  header[10] = 0; // compression
  header[11] = 0; // filter
  header[12] = 0; // no interlace
  const raw = Buffer.alloc(size * (1 + size * 3));
  for (let y = 0; y < size; y++) {
    const row = y * (1 + size * 3);
    raw[row] = 0; // filter: none
    for (let x = 0; x < size; x++) {
      const stripe = Math.abs(x - y) <= 1;
      const i = row + 1 + x * 3;
      raw[i] = stripe ? 255 : r;
      raw[i + 1] = stripe ? 255 : g;
      raw[i + 2] = stripe ? 255 : b;
    }
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk("IHDR", header),
    pngChunk("IDAT", deflateSync(raw)),
    pngChunk("IEND", Buffer.alloc(0)),
  ]);
}

/** A minimal one-page PDF with a few lines of Helvetica text and a real xref. */
function makePdf(title: string, lines: string[]): Buffer {
  const esc = (s: string) => s.replace(/[\\()]/g, (m) => `\\${m}`).replace(/[^\x20-\x7e]/g, "?");
  const text = [
    "BT",
    "/F1 18 Tf",
    "72 760 Td",
    `(${esc(title)}) Tj`,
    "/F1 11 Tf",
    "0 -28 Td",
    ...lines.flatMap((l) => [`(${esc(l)}) Tj`, "0 -16 Td"]),
    "ET",
  ].join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${Buffer.byteLength(text, "latin1")} >>\nstream\n${text}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  let out = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((obj, i) => {
    offsets.push(Buffer.byteLength(out, "latin1"));
    out += `${i + 1} 0 obj\n${obj}\nendobj\n`;
  });
  const xrefAt = Buffer.byteLength(out, "latin1");
  out += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) out += `${String(off).padStart(10, "0")} 00000 n \n`;
  out += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF\n`;
  return Buffer.from(out, "latin1");
}

/** Wraps generated bytes as an upload, like a browser form would send it. */
const asFile = (bytes: Buffer, name: string, type: string) => new File([new Uint8Array(bytes)], name, { type });

async function attach(
  userId: number,
  files: File[],
  maxFiles: number,
  target: { postId: number } | { commentId: number }
) {
  const { prepared, error } = await prepareUploads(userId, files, maxFiles);
  if (error) {
    console.warn(`  (skipped attachment: ${error})`);
    return 0;
  }
  return (await storeUploads(userId, prepared, target)).length;
}

// ---------------------------------------------------------------------------
// People. All fake. Activated accounts can log in with SEED_PASSWORD.
// ---------------------------------------------------------------------------

const people = [
  {
    name: "Aigerim Nurlanova",
    nativeName: "Айгерим Нурланова",
    email: "aigerim.nurlanova@qairu.edu.kz",
    role: "admin",
    sex: "Female",
    classYear: "2029",
    residence: "EXPO B2.2 Cowork",
    birthday: "May 12, 2006",
    hometown: "Almaty",
    highSchool: "NIS Almaty",
    headline: "Building agents & running AI Fridays",
    lookingFor: "Hackathon team, Project collaborators, Friends",
    clubs: "AI Fridays (organizer), Debate Club",
    telegram: "aigerim_demo",
    github: "aigerim-demo",
    courses: "Intro to Programming, Linear Algebra, AI Systems",
    interests: "agents, hackathons, coffee",
    music: "The Weeknd, Dimash",
    books: "Hackers & Painters",
    aboutMe: "Building things at QAIRU. Fake seed account for demos.",
  },
  {
    name: "Dias Bekmuratov",
    nativeName: "Диас Бекмуратов",
    email: "dias.bekmuratov@qairu.edu.kz",
    role: "member",
    sex: "Male",
    classYear: "2029",
    residence: "Student Housing Block A",
    birthday: "January 3, 2005",
    hometown: "Astana",
    highSchool: "RFMSH Astana",
    headline: "Robots, Rust and football on Sundays",
    lookingFor: "Hackathon team, Study partners",
    clubs: "Robotics Club, Football",
    telegram: "dias_demo",
    github: "dias-demo",
    courses: "Intro to Programming, Discrete Math, AI Systems",
    interests: "robotics, football",
    music: "Kanye, Mozart",
    books: "Surely You're Joking, Mr. Feynman",
    aboutMe: "Seed classmate. Not a real person.",
  },
  {
    name: "Madina Satpayeva",
    nativeName: "Мадина Сатпаева",
    email: "madina.satpayeva@qairu.edu.kz",
    role: "member",
    sex: "Female",
    classYear: "2028",
    residence: "EXPO B2.2 Cowork",
    birthday: "August 21, 2004",
    hometown: "Shymkent",
    highSchool: "Bilim-Innovation Shymkent",
    headline: "Speech AI nerd. I make the cheat sheets.",
    lookingFor: "Study partners, Mentorship, Internship tips",
    clubs: "Women in AI, Startup Club",
    telegram: "madina_demo",
    github: "madina-demo",
    courses: "Linear Algebra, Machine Learning, Speech AI",
    interests: "speech AI, startups",
    music: "Lana Del Rey",
    books: "Zero to One",
    aboutMe: "Seed profile for theqairubook demos.",
  },
  {
    name: "Yerasyl Omarov",
    nativeName: "Ерасыл Омаров",
    email: "yerasyl.omarov@qairu.edu.kz",
    role: "member",
    sex: "Male",
    classYear: "2028",
    residence: "Student Housing Block B",
    birthday: "November 9, 2004",
    hometown: "Karaganda",
    highSchool: "Nazarbayev Intellectual School",
    headline: "Computer vision + film photography",
    lookingFor: "Project collaborators, Friends",
    clubs: "Photo Club",
    telegram: "yerasyl_demo",
    github: "yerasyl-demo",
    courses: "AI Systems, Computer Vision, Intro to Programming",
    interests: "CV, photography",
    music: "Radiohead",
    books: "Gödel, Escher, Bach",
    aboutMe: "Fake QAIRU student for directory testing.",
  },
  {
    name: "Sara Iskakova",
    nativeName: "Сара Искакова",
    email: "sara.iskakova@qairu.edu.kz",
    role: "member",
    sex: "Female",
    classYear: "2029",
    residence: "EXPO B2.2 Cowork",
    birthday: "February 28, 2006",
    hometown: "Aktau",
    highSchool: "Daryn Aktau",
    headline: "Proofs, tea, and more proofs",
    lookingFor: "Study partners, Friends",
    clubs: "Math Circle",
    telegram: "sara_demo",
    github: "",
    courses: "Discrete Math, Linear Algebra, Intro to Programming",
    interests: "math olympiads, tea",
    music: "classical playlist",
    books: "How to Prove It",
    aboutMe: "Seed account. Hello from the Caspian.",
  },
  {
    name: "Nursultan Abiyev",
    nativeName: "Нурсултан Абиев",
    email: "nursultan.abiyev@qairu.edu.kz",
    role: "member",
    sex: "Male",
    classYear: "2027",
    residence: "Off-campus Astana",
    birthday: "July 4, 2003",
    hometown: "Kokshetau",
    highSchool: "Lyceum 1",
    headline: "3rd year · ML research · ask me about GPUs",
    lookingFor: "Project collaborators, Internship tips",
    clubs: "ML Reading Group",
    telegram: "nursultan_demo",
    github: "nursultan-demo",
    courses: "Machine Learning, Speech AI, Computer Vision",
    interests: "ML research, Alem cloud",
    music: "Travis Scott",
    books: "Attention Is All You Need (paper)",
    aboutMe: "Third-year seed profile for demos only.",
  },
  {
    name: "Anuar Suleimenov",
    nativeName: "Ануар Сулейменов",
    email: "anuar.suleimenov@qairu.edu.kz",
    role: "member",
    sex: "Male",
    classYear: "2027",
    residence: "Off-campus Astana",
    birthday: "March 15, 2003",
    hometown: "Astana",
    highSchool: "BIL Astana",
    headline: "Backend dev, interned last summer",
    lookingFor: "Mentorship, Internship tips",
    clubs: "Dev Club, Chess",
    telegram: "anuar_demo",
    github: "anuar-demo",
    courses: "AI Systems, Machine Learning, Databases",
    interests: "distributed systems, chess",
    music: "Hans Zimmer",
    books: "Designing Data-Intensive Applications",
    aboutMe: "Seed student account — not a real person.",
  },
  {
    name: "Zarina Temirbek",
    nativeName: "Зарина Темирбек",
    email: "zarina.temirbek@qairu.edu.kz",
    role: "member",
    sex: "Female",
    classYear: "2028",
    residence: "Student Housing Block A",
    birthday: "October 2, 2004",
    hometown: "Pavlodar",
    highSchool: "NIS Pavlodar",
    headline: "Student council · notes hoarder",
    lookingFor: "Friends, Study partners",
    clubs: "Student Council, Volunteering",
    telegram: "zarina_demo",
    github: "",
    courses: "Intro to Programming, Discrete Math, Statistics",
    interests: "student life, volunteering",
    music: "Ninety One",
    books: "Atomic Habits",
    aboutMe: "Seed student account for directory demos.",
  },
];

// Pre-created from the (fake) student list: cannot log in until activated.
const listed: [string, string, string, string][] = [
  ["Arman Zhakupov", "Арман Жакупов", "Male", "2029"],
  ["Dana Kassymova", "Дана Касымова", "Female", "2029"],
  ["Timur Seitkali", "Тимур Сейткали", "Male", "2028"],
  ["Aruzhan Bekova", "Аружан Бекова", "Female", "2029"],
  ["Alikhan Dosmukhamedov", "Алихан Досмухамедов", "Male", "2027"],
  ["Kamila Ospanova", "Камила Оспанова", "Female", "2028"],
  ["Sanzhar Yessenov", "Санжар Есенов", "Male", "2029"],
  ["Tomiris Abdrakhmanova", "Томирис Абдрахманова", "Female", "2027"],
  ["Miras Kuanyshev", "Мирас Куанышев", "Male", "2028"],
  ["Assel Zhumabayeva", "Асель Жумабаева", "Female", "2029"],
  ["Daniyar Serikbayev", "Данияр Серикбаев", "Male", "2028"],
  ["Inkar Mukhtarova", "Инкар Мухтарова", "Female", "2029"],
];

async function upsertActivated(hash: string) {
  const ids: number[] = [];
  for (const [i, p] of people.entries()) {
    const profile = { ...p, status: "Student", school: "QAIRU", privacy: "network" };
    const joinedAt = hoursAgo(24 * (30 - i * 3));
    const [existing] = await db.select().from(users).where(eq(users.email, p.email)).limit(1);
    if (existing) {
      // Refresh the demo profile; never reset a password someone changed locally.
      await db
        .update(users)
        .set({
          ...profile,
          ...(existing.claimedAt ? {} : { passwordHash: hash, claimedAt: joinedAt }),
          referralCode: existing.referralCode ?? makeReferralCode(p.name),
        })
        .where(eq(users.id, existing.id));
      ids.push(existing.id);
      continue;
    }
    const [u] = await db
      .insert(users)
      .values({
        ...profile,
        passwordHash: hash,
        claimedAt: joinedAt,
        memberSince: joinedAt,
        referralCode: makeReferralCode(p.name),
      })
      .returning();
    ids.push(u.id);
    await db.insert(boardEvents).values({
      actorUserId: u.id,
      kind: "joined",
      detail: `${u.name} joined theqairubook`,
      createdAt: joinedAt,
    });
  }
  return ids;
}

async function upsertUnclaimed() {
  const ids: number[] = [];
  for (const [name, nativeName, sex, classYear] of listed) {
    const email = `${name.toLowerCase().replace(" ", ".")}@qairu.edu.kz`;
    const [existing] = await db.select().from(users).where(eq(users.email, email)).limit(1);
    if (existing) {
      ids.push(existing.id);
      continue;
    }
    const [u] = await db
      .insert(users)
      .values({
        name,
        nativeName,
        email,
        sex,
        classYear,
        status: "Student",
        school: "QAIRU",
        passwordHash: "",
        claimedAt: null,
        referralCode: makeReferralCode(name),
      })
      .returning();
    ids.push(u.id);
  }
  return ids;
}

/** Inserts a friendship unless one exists in either direction. */
async function befriend(fromId: number, toId: number, status: "accepted" | "pending", h: number) {
  const [exists] = await db
    .select({ id: friendships.id })
    .from(friendships)
    .where(
      or(
        and(eq(friendships.fromUserId, fromId), eq(friendships.toUserId, toId)),
        and(eq(friendships.fromUserId, toId), eq(friendships.toUserId, fromId))
      )
    )
    .limit(1);
  if (exists) return;
  await db.insert(friendships).values({ fromUserId: fromId, toUserId: toId, status, createdAt: hoursAgo(h) });
  if (status === "accepted") {
    await db.insert(boardEvents).values({
      actorUserId: fromId,
      targetUserId: toId,
      kind: "friend",
      detail: "became friends",
      createdAt: hoursAgo(h),
    });
  }
}

// ---------------------------------------------------------------------------
// Community content: discussions, comments, answers, votes, attachments,
// saved posts, walls, chat, a poke and a referral. All through the real rep
// functions so scores and users.rep stay equal to the ledger.
// ---------------------------------------------------------------------------

async function seedCommunity(ids: number[]) {
  const [aigerim, dias, madina, yerasyl, sara, nursultan, anuar, zarina] = ids;
  const [already] = await db.select({ id: discussionPosts.id }).from(discussionPosts).limit(1);
  if (already) {
    console.log("Discussions already exist — skipping community content.");
    return false;
  }

  const boardRows = await db.select().from(boards);
  const board = (slug: string) => {
    const row = boardRows.find((b) => b.slug === slug);
    if (!row) throw new Error(`Board "${slug}" missing — did ensureSchema run?`);
    return row;
  };

  type Flair = "discussion" | "question" | "material" | "announcement";
  const posts: { key: string; board: string; author: number; h: number; flair: Flair; pinned?: boolean; title: string; body: string; url?: string }[] = [
    {
      key: "welcome",
      board: "general",
      author: aigerim,
      h: 72,
      flair: "announcement",
      pinned: true,
      title: "Welcome to theqairubook 👋 read this first",
      body:
        "This is a calm, students-only space for QAIRU — no feed algorithm, no ads.\n\n" +
        "• Stuck on homework? Post in Homework Help and mark the answer that helped.\n" +
        "• Share notes and PDFs in Study Materials.\n" +
        "• Classmates not here yet show as \"not joined yet\" — copy your invite link from their profile and send it to them.\n\n" +
        "Be kind, credit your sources, and don't post exam answers during the exam 🙂",
    },
    {
      key: "hw-induction",
      board: "homework",
      author: sara,
      h: 22,
      flair: "question",
      title: "Discrete Math HW3 Q5 — strong induction on Fibonacci bound?",
      body: "Need to show F(n) < 2^n for all n ≥ 1. My base case works but the inductive step feels circular. What am I missing?",
    },
    {
      key: "hw-matrix",
      board: "homework",
      author: zarina,
      h: 11,
      flair: "question",
      title: "Is a matrix with a zero eigenvalue always non-invertible?",
      body: "Seems obvious but I can't write it down properly for the LinAlg quiz.",
    },
    {
      key: "coding-oom",
      board: "coding",
      author: yerasyl,
      h: 15,
      flair: "question",
      title: "PyTorch: CUDA out of memory even with batch size 8?",
      body: "Fine-tuning a ResNet-50 on 512x512 images on the lab GPU. Crashes on the second epoch. Already called torch.cuda.empty_cache().",
    },
    {
      key: "coding-setup",
      board: "coding",
      author: dias,
      h: 40,
      flair: "discussion",
      title: "Show your dev setup: editor, terminal, favourite extensions",
      body: "Mine: VS Code + Vim keys, WezTerm, rust-analyzer, Error Lens. Convince me to switch to Neovim.",
    },
    {
      key: "materials-linalg",
      board: "materials",
      author: madina,
      h: 33,
      flair: "material",
      title: "Linear Algebra midterm cheat sheet (eigenvalues, SVD) — PDF",
      body: "Two pages, made it for our study group. Diagram attached too. Corrections welcome!",
    },
    {
      key: "materials-intro",
      board: "materials",
      author: zarina,
      h: 55,
      flair: "material",
      title: "Intro to Programming weeks 1–4 summary notes",
      body: "Loops, functions, lists, dictionaries — with the exercises we did in lab. Python only.",
      url: "https://docs.python.org/3/tutorial/",
    },
    {
      key: "courses-group",
      board: "courses",
      author: madina,
      h: 20,
      flair: "discussion",
      title: "Linear Algebra midterm study group — Thursday 18:00 at B2.2?",
      body: "Going through eigenvalues + SVD past papers. Bring snacks, I'll bring the whiteboard markers.",
    },
    {
      key: "courses-elective",
      board: "courses",
      author: sara,
      h: 30,
      flair: "question",
      title: "Which is harder: Discrete Math or Linear Algebra?",
      body: "Picking electives for next semester and everyone gives me a different answer.",
    },
    {
      key: "projects-speech",
      board: "projects",
      author: nursultan,
      h: 26,
      flair: "discussion",
      title: "Looking for 2 teammates: Kazakh speech recognition demo",
      body: "Fine-tuning a small Whisper model on open Kazakh speech data. Need one person for data cleaning and one for a web demo.",
    },
    {
      key: "career-interview",
      board: "career",
      author: anuar,
      h: 48,
      flair: "question",
      title: "What did your first internship interview actually ask?",
      body: "Got a backend internship interview next week. Was it LeetCode, system design, or just talking about projects?",
    },
    {
      key: "events-fridays",
      board: "events",
      author: aigerim,
      h: 9,
      flair: "discussion",
      title: "AI Fridays this week: build an agent in 90 minutes 🤖",
      body: "Teams of 2-3. Best demo gets pizza and eternal glory. Sign up in the comments.",
    },
    {
      key: "memes-3am",
      board: "memes",
      author: dias,
      h: 4,
      flair: "discussion",
      title: "When the model finally converges at 3am and you have class at 9",
      body: "",
    },
  ];

  const postIds: Record<string, number> = {};
  for (const p of posts) {
    const b = board(p.board);
    const [row] = await db
      .insert(discussionPosts)
      .values({
        boardId: b.id,
        authorUserId: p.author,
        title: p.title,
        body: p.body,
        url: p.url ?? "",
        flair: p.flair,
        pinned: p.pinned ?? false,
        createdAt: hoursAgo(p.h),
      })
      .returning();
    postIds[p.key] = row.id;
    await db.insert(boardEvents).values({
      actorUserId: p.author,
      kind: "discussion",
      detail: JSON.stringify({ postId: row.id, slug: b.slug, title: row.title }),
      createdAt: hoursAgo(p.h),
    });
  }

  async function comment(
    post: string,
    author: number,
    body: string,
    h: number,
    parent?: { id: number; authorUserId: number }
  ) {
    const postId = postIds[post];
    const [row] = await db
      .insert(discussionComments)
      .values({ postId, parentId: parent?.id ?? null, authorUserId: author, body, createdAt: hoursAgo(h) })
      .returning();
    const [op] = await db
      .update(discussionPosts)
      .set({ commentCount: sql`${discussionPosts.commentCount} + 1` })
      .where(eq(discussionPosts.id, postId))
      .returning({ authorUserId: discussionPosts.authorUserId });
    if (parent) await awardReply(parent.authorUserId, author, "comment", parent.id);
    else await awardReply(op.authorUserId, author, "post", postId);
    return row;
  }

  // Welcome
  const w1 = await comment("welcome", madina, "Finally a place that isn't 14 group chats. Thanks for setting this up!", 70);
  await comment("welcome", aigerim, "That was exactly the idea 😄 invite your lab partners!", 69, w1);
  await comment("welcome", yerasyl, "Is there a dark mode? (kidding, the blue is perfect)", 50);

  // Homework: induction (accepted answer)
  await comment("hw-induction", dias, "Did you use two base cases? Fibonacci needs F(1) and F(2) since the step uses n-1 and n-2.", 21);
  const h2 = await comment(
    "hw-induction",
    nursultan,
    "Assume F(k) < 2^k for all k ≤ n. Then F(n+1) = F(n) + F(n-1) < 2^n + 2^(n-1) < 2^n + 2^n = 2^(n+1). Base cases n=1,2 cover the start. Not circular — you're using earlier cases, not the one you're proving.",
    20
  );
  const h3 = await comment("hw-induction", sara, "OH. I was only assuming k = n. Thank you!!", 19, h2);
  await comment("hw-induction", nursultan, "Classic trap, happened to me too in first year.", 18, h3);
  await setAcceptedAnswer(postIds["hw-induction"], h2.id, sara);

  // Homework: eigenvalue (still open)
  const m1 = await comment("hw-matrix", madina, "Yes: det(A) is the product of the eigenvalues, so one zero makes det(A) = 0.", 10);
  await comment("hw-matrix", zarina, "Would Av = 0 for a nonzero v also count as a proof?", 9, m1);

  // Coding: OOM (accepted answer + screenshot on a comment)
  const o1 = await comment(
    "coding-oom",
    dias,
    "Wrap validation in torch.no_grad() and make sure you don't append the loss tensor to a list — use loss.item(). That keeps the whole graph alive between epochs.",
    14
  );
  const o2 = await comment("coding-oom", yerasyl, "Here's nvidia-smi right before it dies:", 13.5, o1);
  await comment("coding-oom", nursultan, "Also try mixed precision (torch.autocast) — roughly halves activation memory.", 13);
  await comment("coding-oom", yerasyl, "It was losses.append(loss) 🤦 fixed, thanks Dias!", 12, o2);
  await setAcceptedAnswer(postIds["coding-oom"], o1.id, yerasyl);

  // Coding: setup
  const s1 = await comment("coding-setup", anuar, "Neovim + tmux. Once you stop reaching for the mouse you never go back.", 39);
  await comment("coding-setup", dias, "That's what they all say…", 38, s1);
  await comment("coding-setup", madina, "JetBrains for Python, VS Code for everything else. Fight me.", 36);

  // Materials
  const l1 = await comment("materials-linalg", sara, "This saved my evening. Small typo: SVD is U Σ V^T, not V.", 31);
  await comment("materials-linalg", madina, "Good catch, fixed in my notes — will re-upload after the midterm.", 30, l1);
  await comment("materials-intro", dias, "The dictionary exercises are gold. Thanks Zarina!", 50);

  // Courses
  const c1 = await comment("courses-group", sara, "I'm in. Can we also cover determinants?", 19);
  await comment("courses-group", madina, "Sure, first 30 minutes on determinants.", 18, c1);
  await comment("courses-group", dias, "Will anyone take notes for people in the late lab?", 17);
  const e1 = await comment("courses-elective", nursultan, "Discrete is harder to start, LinAlg is harder to finish.", 28);
  await comment("courses-elective", sara, "That is somehow the most helpful answer so far", 27, e1);
  await comment("courses-elective", anuar, "Take Discrete first — proofs make Linear Algebra much easier.", 25);

  // Projects, career, events, memes
  const p1 = await comment("projects-speech", madina, "I'd love to do the data cleaning part! I did speech preprocessing last term.", 24);
  await comment("projects-speech", nursultan, "Perfect, DM me on chat.", 23, p1);
  await comment("projects-speech", yerasyl, "I can hack together the web demo if nobody else wants it.", 22);
  const i1 = await comment(
    "career-interview",
    nursultan,
    "Mine was 1 easy algorithm question, then 30 minutes on a project from my GitHub. Know your own code really well.",
    46
  );
  await comment("career-interview", anuar, "Good to know, cleaning up my README tonight.", 45, i1);
  await comment("career-interview", zarina, "The career center does mock interviews on Tuesdays btw.", 44);
  await setAcceptedAnswer(postIds["career-interview"], i1.id, anuar);
  const f1 = await comment("events-fridays", dias, "Me + Yerasyl are in. Can we use any framework?", 8);
  const f2 = await comment("events-fridays", aigerim, "Anything goes, as long as it runs live on stage 😄", 7, f1);
  await comment("events-fridays", yerasyl, "Bringing my Raspberry Pi. No promises it survives.", 6, f2);
  const f3 = await comment("events-fridays", madina, "Is there a speech track? I'd love to demo a voice agent.", 5);
  await comment("events-fridays", aigerim, "Yes! Speech demos welcome.", 5, f3);
  await comment("events-fridays", nursultan, "Count me in, looking for a teammate who knows CV.", 3);
  await comment("memes-3am", madina, "loss.backward() and so did my sleep schedule", 3);

  // Attachments: a cheat sheet PDF + diagram PNG on a material post, a screenshot on a comment.
  const cheatSheet = makePdf("Linear Algebra Cheat Sheet (demo)", [
    "Eigenvalues: det(A - lambda I) = 0",
    "Eigenvectors: (A - lambda I) v = 0, v != 0",
    "det(A) = product of eigenvalues, tr(A) = sum of eigenvalues",
    "SVD: A = U Sigma V^T, U and V orthogonal",
    "Rank = number of nonzero singular values",
    "Fake study material generated by the theqairubook seed.",
  ]);
  let attached = 0;
  attached += await attach(
    madina,
    [
      asFile(cheatSheet, "linalg-cheat-sheet.pdf", "application/pdf"),
      asFile(makePng(16, [59, 89, 152]), "svd-diagram.png", "image/png"),
    ],
    MEDIA_LIMITS.filesPerPost,
    { postId: postIds["materials-linalg"] }
  );
  attached += await attach(
    yerasyl,
    [asFile(makePng(16, [34, 139, 34]), "nvidia-smi.png", "image/png")],
    MEDIA_LIMITS.filesPerComment,
    { commentId: o2.id }
  );

  // Votes: deterministic pseudo-random, weighted toward upvotes.
  const voters = [aigerim, dias, madina, yerasyl, sara, nursultan, anuar, zarina];
  let seed = 7;
  const rand = () => (seed = (seed * 9301 + 49297) % 233280) / 233280;
  const allPosts = await db.select().from(discussionPosts);
  const allComments = await db.select().from(discussionComments);
  for (const p of allPosts) {
    for (const v of voters) {
      if (v !== p.authorUserId && rand() < 0.8) await castVote(v, "post", p.id, rand() < 0.9 ? 1 : -1);
    }
  }
  for (const cm of allComments) {
    for (const v of voters) {
      if (v !== cm.authorUserId && rand() < 0.45) await castVote(v, "comment", cm.id, rand() < 0.88 ? 1 : -1);
    }
  }

  // Aigerim's saved posts
  for (const key of ["materials-linalg", "coding-oom", "materials-intro"]) {
    await db.insert(savedPosts).values({ userId: aigerim, postId: postIds[key] }).onConflictDoNothing();
  }

  // Walls (activated profiles only), replies and votes
  async function wall(profile: number, author: number, body: string, h: number, parent?: { id: number; authorUserId: number }) {
    const [row] = await db
      .insert(wallPosts)
      .values({ profileUserId: profile, authorUserId: author, parentId: parent?.id ?? null, body, createdAt: hoursAgo(h) })
      .returning();
    if (parent) {
      await awardReply(parent.authorUserId, author, "wall", parent.id);
    } else if (profile !== author) {
      await db.insert(boardEvents).values({
        actorUserId: author,
        targetUserId: profile,
        kind: "wall",
        detail: body.slice(0, 140),
        createdAt: hoursAgo(h),
      });
    }
    return row;
  }
  const fridays = await wall(aigerim, dias, "See you at AI Fridays?", 12);
  const fr1 = await wall(aigerim, aigerim, "Obviously! Save me a seat near the projector.", 11, fridays);
  await wall(aigerim, sara, "Can I join you two?", 10, fr1);
  const welcomeWall = await wall(dias, aigerim, "Welcome to QAIRU — this wall still works like 2004.", 60);
  await wall(dias, dias, "The poke button is the best feature, no notes.", 59, welcomeWall);
  const lab = await wall(madina, yerasyl, "Lab partners for Computer Vision?", 34);
  await wall(madina, madina, "Only if you do the camera calibration part 😅", 33, lab);
  await wall(sara, zarina, "Thanks for the study group snacks yesterday!", 16);
  for (const v of [madina, sara, yerasyl]) await castVote(v, "wall", fridays.id, 1);
  for (const v of [dias, madina]) await castVote(v, "wall", fr1.id, 1);
  for (const v of [sara, nursultan]) await castVote(v, "wall", welcomeWall.id, 1);
  await castVote(aigerim, "wall", lab.id, 1);

  // A poke
  await db.insert(pokes).values({ fromUserId: yerasyl, toUserId: aigerim, createdAt: hoursAgo(6) });

  // A chat between Aigerim and Madina
  const chat: [number, number, string, number][] = [
    [madina, aigerim, "hey! are you coming to the LinAlg study group?", 26],
    [aigerim, madina, "yes!! can I bring Dias?", 25.9],
    [madina, aigerim, "of course, the more the merrier", 25.8],
    [aigerim, madina, "also do you have the SVD notes from Tuesday?", 2],
    [madina, aigerim, "uploaded the cheat sheet to Study Materials 📎", 1.9],
  ];
  for (const [from, to, body, h] of chat) {
    await db.insert(messages).values({ fromUserId: from, toUserId: to, body, read: h > 1.95, createdAt: hoursAgo(h) });
  }

  // Sara activated through Aigerim's invite link
  await db.update(users).set({ referredByUserId: aigerim }).where(eq(users.id, sara));
  await befriend(aigerim, sara, "accepted", 40);
  const earned = await awardReferral(aigerim, sara);
  await db.insert(boardEvents).values({
    actorUserId: sara,
    targetUserId: aigerim,
    kind: "referral",
    detail: earned ? `+${earned} rep` : "",
    createdAt: hoursAgo(40),
  });

  console.log(`Attached ${attached} demo file(s).`);
  return true;
}

async function count(table: typeof users | typeof discussionPosts | typeof discussionComments | typeof media | typeof votes | typeof friendships | typeof messages | typeof wallPosts | typeof repEvents) {
  const [row] = await db.select({ n: sql<number>`count(*)::int` }).from(table);
  return row.n;
}

async function main() {
  console.log("Seeding theqairubook (local dev data, all fake)…");
  await ensureSchema();
  const hash = hashPassword(SEED_PASSWORD);

  const active = await upsertActivated(hash);
  const unclaimed = await upsertUnclaimed();

  // Friendships among activated students
  const pairs: [number, number, number][] = [
    [0, 1, 300],
    [0, 2, 290],
    [1, 3, 280],
    [2, 3, 260],
    [1, 4, 240],
    [3, 5, 220],
    [2, 5, 200],
    [5, 6, 180],
    [0, 7, 160],
    [4, 7, 140],
    [2, 4, 120],
  ];
  for (const [a, b, h] of pairs) await befriend(active[a], active[b], "accepted", h);

  // Pending requests: activated students -> classmates who haven't joined yet
  await befriend(active[0], unclaimed[0], "pending", 30);
  await befriend(active[0], unclaimed[1], "pending", 28);
  await befriend(active[2], unclaimed[3], "pending", 20);
  // …and one pending request between two members
  await befriend(active[6], active[0], "pending", 8);

  const seededCommunity = await seedCommunity(active);

  const [activated] = await db
    .select({ n: sql<number>`count(*)::int` })
    .from(users)
    .where(sql`${users.claimedAt} is not null`);
  console.log("");
  console.log(`Users: ${await count(users)} (${activated.n} activated, rest not joined yet)`);
  console.log(`Friendships: ${await count(friendships)}`);
  console.log(
    `Posts: ${await count(discussionPosts)} · comments: ${await count(discussionComments)} · votes: ${await count(votes)} · media: ${await count(media)}`
  );
  console.log(`Wall posts: ${await count(wallPosts)} · messages: ${await count(messages)} · rep events: ${await count(repEvents)}`);
  if (!seededCommunity) console.log("(community content was already present)");
  console.log(`Password for all activated seed accounts: ${SEED_PASSWORD}`);
  console.log("Demo login (admin): aigerim.nurlanova@qairu.edu.kz / qairu123");
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
